### ISSUE TITLE
Some notes are rendering the wrong note type in Note class.

### ISSUE THREAD

**Issue by KazumaKun1** [Tunnelbliick/maniaModCharts#16]
![redred](https://github.com/Tunnelbliick/notosu/assets/121232570/b975fc77-9105-4c30-8a72-cb0cd0ba359b)

Hello, 
I'm trying to test the v2.11 and I found this issue. These notes supposed to be red & blue (1 & 2) alternatively but all of them are set on red (1). I tried to redownload it and install it again but it's the same issue.
I did try to debug this and my god, doing debugging using only Log function from storybrew is tedious (I prefer using writeLine function or using breakpoints) and I suspect that there's something weird going on the IsCloseTo function because the loops always stops when the divisions = 1 and not failing on checking on the rest of the divisions (2,3,4,8,12,16).

Debug: 

> Status: Ready
Log:
NoteType = 1, StartTime = 19187, Cycle = 60, adjustedTime = 240, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19346, Cycle = 61, adjustedTime = 83, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19505, Cycle = 61, adjustedTime = 242, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19663, Cycle = 62, adjustedTime = 84, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19028, Cycle = 60, adjustedTime = 81, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19822, Cycle = 62, adjustedTime = 243, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19822, Cycle = 62, adjustedTime = 243, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 18870, Cycle = 59, adjustedTime = 238, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19267, Cycle = 61, adjustedTime = 4, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19425, Cycle = 61, adjustedTime = 162, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19584, Cycle = 62, adjustedTime = 5, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1
NoteType = 1, StartTime = 19743, Cycle = 62, adjustedTime = 164, beatDuration = 315.789473684211, baseTick = 315.789473684211, IsClose = True, Cycle = 0, ExpectedValue = 0, Multiplier = 1

Even though I probably found the root cause, i don't have a clue on what is the purpose of the IsCloseTo nor how to fix it.

Here's the full video of the issue.
https://www.youtube.com/watch?v=46OmG3yzPb8

I also want to refactor this 
```C#      

            if (IsCloseTo(adjustedTime, beatDuration, 32))  // 1/3 rhythms
            {
                this.noteType = 16;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 24))  // 1/3 rhythms
            {
                this.noteType = 12;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 16))  // 1/3 rhythms
            {
                this.noteType = 16;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 12))  // 1/3 rhythms
            {
                this.noteType = 12;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 4))  // 1/3 rhythms
            {
                this.noteType = 4;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 3))  // 1/3 rhythms
            {
                this.noteType = 3;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 2))  // 1/3 rhythms
            {
                this.noteType = 2;  // Whole tick
            }
            if (IsCloseTo(adjustedTime, beatDuration, 1))  // 1/3 rhythms
            {
                this.noteType = 1;  // Whole tick
            }

            noteTypeDebug = noteType;
            cycleDebug = cycle;
            adjustedTimeDebug = adjustedTime;
            beatDurationDebug = beatDuration;

            OsbSprite sprite = null;

            if (isColored == false)
            {
                switch (this.noteType)
                {
                    case 1:
                        sprite = layer.CreateSprite("sb/sprites/1.png");
                        break;
                    case 2:
                        sprite = layer.CreateSprite("sb/sprites/2.png");
                        break;
                    case 3:
                        sprite = layer.CreateSprite("sb/sprites/3.png");
                        break;
                    case 4:
                        sprite = layer.CreateSprite("sb/sprites/4.png");
                        break;
                    case 12:
                        sprite = layer.CreateSprite("sb/sprites/12.png");
                        break;
                    case 16:
                        sprite = layer.CreateSprite("sb/sprites/16.png");
                        break;
                    default:
                        this.noteType = 1;
                        sprite = layer.CreateSprite("sb/sprites/1.png");
                        break;
                }
            }
            else
            {
                sprite = layer.CreateSprite("sb/sprites/arrow.png");
            }
```

Into this for better readability
```C#
            int[] divisions = {16, 12, 4, 3, 2, 1};

            OsbSprite sprite = null;

            foreach (int noteType in divisions) {
                if (IsCloseTo(adjustedTime, beatDuration, noteType))
                {
                    this.noteType = noteType;
                    sprite = !isColored ? layer.CreateSprite($"sb/sprites/{noteType}.png") : layer.CreateSprite("sb/sprites/arrow.png");
                    break;
                } else {
                    this.noteType = 1;
                    sprite = layer.CreateSprite("sb/sprites/arrow.png");
                }
            }
```
 
But i don't understand why is there a condition that checks for 32 and 24 and sets the note type to 16 & 12? I think osu editor is only limited up to 16 unless I didn't know that mappers finds a way to put notes in 24 & 32.
I'm hesitant to do pull request because of this and the issue above.

**Comment by Tunnelbliick** [comment]
@KazumaKun1 it works fine in my v2.11 test.
main things for beatmap snapping is BPM and offset that you set in the note initialization.

offset is basically the same as in OSU.

can you share your Playfield intilization aswell as the .osz?

**Comment by Tunnelbliick** [comment]
> But i don't understand why is there a condition that checks for 32 and 24 and sets the note type to 16 & 12? I think osu editor is only limited up to 16 unless I didn't know that mappers finds a way to put notes in 24 & 32.

Conversion. the check basically just checks for multiples, whilst not common in mania it is common as well it made the code less error prone.

looking at the video it seems like the offset is wrong that is passed to the noteinitializer, which causes weird snaps aswel as mainly fallback to be used.

also u can @ me on storyboard banquet aswell if you have issues

@Tunnelblick there

**Comment by KazumaKun1** [comment]
> @KazumaKun1 it works fine in my v2.11 test. main things for beatmap snapping is BPM and offset that you set in the note initialization.
> 
> offset is basically the same as in OSU.
> 
> can you share your Playfield intilization aswell as the .osz?
> looking at the video it seems like the offset is wrong that is passed to the noteinitializer, which causes weird snaps aswel as mainly fallback to be used.

oh, I didn't set the bpm and offset correctly in the code (the bpm is set to 190 instead of 189 and offset is set to 0 instead of 775. It works now.
This is honestly embarrassing since I spent an hour on why this happens and the issue was due to this simple mistake.  I apologize.

I think we can close the issue now.  

> > But i don't understand why is there a condition that checks for 32 and 24 and sets the note type to 16 & 12? I think osu editor is only limited up to 16 unless I didn't know that mappers finds a way to put notes in 24 & 32.
> 
> Conversion. the check basically just checks for multiples, whilst not common in mania it is common as well it made the code less error prone.
> 

oh okay, i will probably continue checking and cleaning the code.

> also u can @ me on storyboard banquet aswell if you have issues
> 
> @Tunnelblick there

Okay, i will add you tomorrow on my time since it's midnight here and raise any concerns to you instead of creating an issue here.

**Comment by Tunnelbliick** [comment]
I appreciate any help on clean code since currently the codebase is a mess.
